### ISSUE TITLE
no recipe

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [cjburkey01/TranslocationMod#1]
recipe for the translocator block is simply absent in the version "transloc-1.12.2_1.0.3.jar"

**Comment by cjburkey01** [comment]
Silly me, never even tested the recipe. I'll see what I can do, thanks for the info.

**Comment by cjburkey01** [comment]
Ok, I put the recipe in the wrong folder. Should be fixed now, you can download the latest version from here: https://minecraft.curseforge.com/projects/translocation-mod/files/2501005

This will be compatible with previous worlds.

**Comment by TheGuyFromTheInternet** [comment]
Thank you :D
